document.addEventListener('DOMContentLoaded', () => {
    const imageList = document.getElementById('imageList');
    const imageSearch = document.getElementById('imageSearch');
    const imageCount = document.getElementById('imageCount');
    const welcomeScreen = document.getElementById('welcomeScreen');
    const imagePreview = document.getElementById('imagePreview');
    const mainImage = document.getElementById('mainImage');
    const currentImageName = document.getElementById('currentImageName');
    const currentImageMeta = document.getElementById('currentImageMeta');
    const downloadBtn = document.getElementById('downloadBtn');
    const copyLinkBtn = document.getElementById('copyLinkBtn');
    const loader = document.getElementById('loader');
    const toast = document.getElementById('toast');

    let images = [];
    let activeItem = null;

    // Fetch images.json generated by the build script
    async function fetchImages() {
        try {
            const response = await fetch('images.json');
            if (!response.ok) throw new Error('Failed to load images.json');
            images = await response.json();
            renderList(images);
            setTimeout(() => {
                loader.classList.add('hidden');
            }, 500);
        } catch (error) {
            console.error('Error fetching images:', error);
            loader.innerHTML = `<p style="color: #ef4444">Error loading repository. Make sure build.js has run.</p>`;
        }
    }

    function renderList(list) {
        imageList.innerHTML = '';
        list.forEach(img => {
            const li = document.createElement('li');
            li.className = 'image-item';
            li.innerHTML = `
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>
                <span>${img.name}</span>
            `;
            li.addEventListener('click', () => selectImage(img, li));
            imageList.appendChild(li);
        });
        imageCount.textContent = `${list.length} images found`;
    }

    function selectImage(img, element) {
        // Update UI state
        if (activeItem) activeItem.classList.remove('active');
        element.classList.add('active');
        activeItem = element;

        // Show preview
        welcomeScreen.classList.add('hidden');
        imagePreview.classList.remove('hidden');

        // Load image
        mainImage.src = `Img/${img.name}`;
        currentImageName.textContent = img.name;
        
        // Format metadata
        const date = new Date(img.lastModified).toLocaleDateString();
        currentImageMeta.textContent = `Size: ${img.size} | Added: ${date}`;
        
        // Update download link
        downloadBtn.href = `Img/${img.name}`;
    }

    // Search functionality
    imageSearch.addEventListener('input', (e) => {
        const query = e.target.value.toLowerCase();
        const filtered = images.filter(img => img.name.toLowerCase().includes(query));
        renderList(filtered);
    });

    // Copy direct link
    copyLinkBtn.addEventListener('click', () => {
        const fullUrl = window.location.origin + '/' + mainImage.getAttribute('src');
        navigator.clipboard.writeText(fullUrl).then(() => {
            showToast('Link copied to clipboard!');
        });
    });

    function showToast(message) {
        toast.textContent = message;
        toast.classList.remove('hidden');
        setTimeout(() => {
            toast.classList.add('hidden');
        }, 2000);
    }

    // Initialize
    fetchImages();
});
